#!/usr/bin/bash
# Digital Audio Extraction & FAAC Encoder (a RipIT wrapper)

# Lead
echo -e "${0##*/} — Digital Audio Extraction & FAAC Encoder (a RipIT wrapper)\n"

# Help
help_prnt () {
cat << EOF
 ${0##*/} is a bare-essential Audio CD ripper and AAC encoder. Permanent 
 settings define in the config file "~/.ripit/config" or "/etc/ripit/config".
 Audio encoding quality definitions are listed below. This help message can be
 permanently removed on usage with the -H option.

   Preset    FAC  Bitrate 
   --------  ---  --------
   voice      55   ~64kbps
   medium    100  ~128kbps
   standard  150  ~175kbps
   extreme   320  ~240kbps
   insane    500  ~270kbps

EOF
}
if [ "$1" = -H ] ; then
   [ ! -f ~/.config/${0##*/}-help ] && touch ~/.config/${0##*/}-help
else
   [ -n "$1" ] && help_prnt
   [ -z "$1" ] && [ ! -f ~/.config/${0##*/}-help ] && help_prnt
fi

# Output directory
ud=~/.config/user-dirs.dirs ; [ -f $ud ] && source $ud ; musicdir=$XDG_MUSIC_DIR
while true ; do
  read -p "- Output directory? [$XDG_MUSIC_DIR]:  " outputdir
  [ -z "$outputdir" ] && outputdir="$musicdir"                             
  if [ ! -d "$outputdir" ] ; then
     echo "* Nonexistent directory."
  else
     break
  fi
done

# Encoding quality
while true ; do
  read -p \
    "- Encoding quality? (voice, medium, standard, extreme, insane):  "  \
    audio_quality
  [ "$audio_quality" = voice    -o "$audio_quality" = v ] \
    && audio_quality=55  && break
  [ "$audio_quality" = medium   -o "$audio_quality" = m ] \
    && audio_quality=100 && break
  [ "$audio_quality" = standard -o "$audio_quality" = s ] \
    && audio_quality=150 && break
  [ "$audio_quality" = extreme  -o "$audio_quality" = e ] \
    && audio_quality=320 && break
  [ "$audio_quality" = insane   -o "$audio_quality" = i ] \
    && audio_quality=500 && break
  echo "* Nonexistent quality."
done

# Cover art
while true ; do
  read -p "- Coverart embed? [/tmp/cover.jpg] (y/n):  " yn
  case $yn in
    [Yy] ) if [ ! -f "/tmp/cover.jpg" ]; then
              echo "* Nonexistent image."
           else
           #coverart=1; break; fi ;;
           coverart="--coverart=1 --coverpath '/tmp/cover.jpg'"
              break
           fi ;;
    [Nn] ) coverart="--coverart=0"
           break ;;
    *    ) echo "* Select (y)es or (n)o."
  esac
done

# Audiobook
while true ; do
  read -p "- Audiobook CD? (y/n):  " yn
  case $yn in
    [Yy] ) book=1
           break ;;
    [Nn] ) book=0
           break ;;
    *    ) echo "Select (y)es or (n)o."
  esac
done

# Loop
while true; do
  read -p "- Multiple CDs? (y/n):  " yn
  case $yn in
    [Yy] ) loop=1
           break ;;
    [Nn] ) loop=0
           break ;;
    *    ) echo "* Select (y)es or (n)o."
  esac
done

ripit --outputdir="$outputdir" \
      --coder 3 --quality "$audio_quality" --faacopt "-s" \
      "$coverart"  \
      --book=$book \
      --loop=$loop