#!/usr/bin/bash
# Digital Audio Extraction and MP3 Encoder (a RipIT wrapper).

# Lead
echo "${0##*/} — Digital Audio Extraction and MP3 Encoder (a RipIT wrapper)."
echo

# Help
help_prnt () {
cat << EOF
 ${0##*/} is a bare-essential Audio CD "ripper" and MP3 encoder. For permanent
 settings use the configuration file (~/.ripit/config or /etc/ripit/config).
 Audio encoding quality definitions can be found in the the lame manual,
 PRESETS section. Automatic display of the help message can be dismissed with
 the -H option.

EOF
}
if [ "$1" = -H ]; then
  [ ! -f ~/.config/${0##*/}-help ] && touch ~/.config/${0##*/}-help
else
  [ -n "$1" ] && help_prnt
  [ -z "$1" ] && [ ! -f ~/.config/${0##*/}-help ] && help_prnt
fi

# Output directory option
ud=~/.config/user-dirs.dirs; [ -f $ud ] && source $ud; musicdir=$XDG_MUSIC_DIR
while true; do
  read -p "- Output directory? [$XDG_MUSIC_DIR]:  " outputdir
  [ -z "$outputdir" ] && outputdir="$XDG_MUSIC_DIR"                             
  if [ ! -d "$outputdir" ]; then
    echo "* Nonexistent directory."
  else
    break
  fi
done

# Encoding quality option
while true; do
  read -p \
    "- Encoding quality? (voice, medium, standard, extreme, insane):  "  \
    audio_quality
  [ "$audio_quality" = voice    -o "$audio_quality" = v ] && audio_quality=64
  [ "$audio_quality" = 64       -o \
    "$audio_quality" = medium   -o "$audio_quality" = m -o \
    "$audio_quality" = standard -o "$audio_quality" = s -o \
    "$audio_quality" = extreme  -o "$audio_quality" = e -o \
    "$audio_quality" = insane   -o "$audio_quality" = i ] && break
  echo "* Select (voice, medium, standard, extreme, insane)."
done

# Cover art option
while true; do
  read -p "- Coverart embed? [/tmp/cover.jpg] (y/n):  " yn
  case $yn in
    [Yy] ) if [ ! -f "/tmp/cover.jpg" ]; then
             echo "* Nonexistent image."
           else
           coverart=1; break; fi ;;
    [Nn] ) coverart=0; break ;;
    *    ) echo "* Select (y)es or (n)o."
  esac
done

# Loop option
while true; do
  read -p "- Multiple CDs? (y/n):  " yn
  case $yn in
    [Yy] ) loop=1; break ;;
    [Nn] ) loop=0; break ;;
    *    ) echo "* Select (y)es or (n)o."
  esac
done

ripit --outputdir="$outputdir"              \
      --preset=$audio_quality --vbrmode=new \
      --coverart=$coverart --coverpath '/tmp/cover.jpg' \
      --loop=$loop                          \
      1-a
